server:
  port: ${PORT:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL}
          username: ${REPO_ACCOUNT_NAME}
          password: ${REPO_ACCOUNT_PASSWORD}
  application:
    name: hyh-config-server

